swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
#API People - TEST //TODO supprimer
  /people:
    get:
      operationId: "api.people.read"
      tags:
        - "People"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"
#API Laumio
  ## FONCTION : RAINBOW #########################
  # rainbow All
  /laumio/all/rainbow:
    get:
      operationId: "api.laumio.rainbowAll"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Animation arc-en-ciel sur toutes les lampes Laumios"
      responses:
        200:
          description: "Animation success"
          schema:
            type: "string"
  # rainbow One
  /laumio/{nom}/rainbow:
    get:
      operationId: "api.laumio.rainbow"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Animation arc-en-ciel sur une lampe Laumio"
      parameters:
        - name: nom
          in: path
          description: Nom de la lampe Laumio à animer
          type: string
          required: True
      responses:
        200:
          description: "Animation success"
          schema:
            type: "string"
  # All Laumios
  /laumio/names:
    get:
      operationId: "api.laumio.allLaumios"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Retourne les noms des Laumios"
      responses:
        200:
          description: "Animation success"
          schema:
            type: "string"