swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
#API People - TEST //TODO supprimer
  /people:
    get:
      operationId: "api.people.read"
      tags:
        - "People"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"
#API Laumio
  ## FONCTION : RAINBOW #########################
  # rainbow All
  /laumio/all/rainbow:
    get:
      operationId: "api.laumio.rainbowAll"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Animation arc-en-ciel sur toutes les lampes Laumios"
      responses:
        200:
          description: "Animation success"
          schema:
            type: "string"
  # rainbow One
  /laumio/{laumios}/rainbow:
    get:
      operationId: "api.laumio.rainbowGroupe"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Animation arc-en-ciel sur une lampe Laumio"
      parameters:
        - name: laumios
          in: path
          description: Nom de la lampe Laumio à animer
          type: string
          required: True
      responses:
        200:
          description: "Animation success"
          schema:
            type: "string"
  # rainbow Group
  /laumio/group/rainbow:
    get:
      operationId: "api.laumio.rainbowGroup"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Animation arc-en-ciel sur une lampe Laumio"
      parameters:
        - name: laumios
          in: body
          description: array Laumio composé d'une liste des noms à animer
          type: array
          required: True
      responses:
        200:
          description: "Animation success"
          schema:
            type: "string"
  ## FONCTION : FILL #########################
  # fill All
  /laumio/all/fill:
    post:
      operationId: "api.laumio.fillAll"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Remplissage avec une couleur sur toutes les lampes Laumios"
      parameters:
        - name: couleur
          in: body
          description: Couleur RGB à afficher dans les Laumios, au format {couleur = [R, G, B]} dans JSon
          type: array
          required: True
      responses:
        200:
          description: "Fill success"
          schema:
            type: "string"
  # fill One
  /laumio/{nom}/fill:
    post:
      operationId: "api.laumio.fill"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Remplissage avec une couleur sur une lampe Laumio"
      parameters:
        - name: nom
          in: path
          description: Nom de la lampe Laumio à remplir
          type: string
          required: True
        - name: couleur
          in: body
          description: Couleur RGB à afficher dans les Laumios, au format {couleur = [R, G, B]} dans JSon
          type: array
          required: True
      responses:
        200:
          description: "Fill success"
          schema:
            type: "string"
  # fill Group
  /laumio/group/fill:
    post:
      operationId: "api.laumio.fill"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Remplissage avec une couleur sur une lampe Laumio"
      parameters:
        - name: nom
          in: path
          description: Nom de la lampe Laumio à remplir
          type: string
          required: True
        - name: couleur
          in: body
          description: Couleur RGB à afficher dans les Laumios, au format {couleur = [R, G, B]} dans JSon
          type: array
          required: True
      responses:
        200:
          description: "Fill success"
          schema:
            type: "string"

            type: object
          properties:
              nom:
                type: string
                description: nom du Laumio
              couleur:
                type: array
                description: couleur [R, G, B] à affecter
          required: True
  ## FONCTION : ALL NAME #########################
  # All Laumios
  /laumio/names:
    get:
      operationId: "api.laumio.allLaumios"
      tags:
        - "Laumio"
      summary: "Lampe Laumio à leds multiples"
      description: "Retourne les noms des Laumios"
      responses:
        200:
          description: "Récupération success"
          schema:
            type: "string"